# 1) Write a Python Program to Add Two Matrices?


In [1]:
import numpy as np

In [101]:
class soln1:
    
    def __init__(self,mat1,mat2):
        self.m1 = mat1
        self.m2 = mat2
        self.res = []
        
    def mAdd(self):
        
        #Check dimension of matrix
        try:
            for i,j in zip(self.m1.shape,self.m2.shape):
                if i-j != 0:
                    raise Exception(f"dimensions not same, cant add")
            
            # Dimension satisfied perform addition.
            else:
                for i,j in zip(self.m1,self.m2):
                    for i1,j1 in zip(i,j):
                        self.res.append(i1+j1)
                        
                return np.array(self.res)
                            
        except Exception as e:
            print(e)
            

In [104]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])
obj = soln1(mat1,mat2)
obj.mAdd()

array([ 6,  8, 10, 12])

In [109]:
mat1 = np.array([[1,2,2],[3,4,5]])
mat2 = np.array([[5,6],[7,8]])
obj = soln1(mat1,mat2)
obj.mAdd()

dimensions not same, cant add


In [110]:
mat1 = np.random.randint(100,size=(2,5))
mat2 = np.random.randint(100,size =(5,2))
obj = soln1(mat1,mat2)
obj.mAdd()

dimensions not same, cant add


In [111]:
mat1 = np.random.randint(100,size=(3,5))
mat2 = np.random.randint(100,size =(3,5))
obj = soln1(mat1,mat2)
obj.mAdd()

array([102, 103,  41, 124,  61,  37, 147, 142,  83, 132, 117, 129, 158,
        74,  98])

In [112]:
mat1 = np.random.randint(100,size=(2,3,5))
mat2 = np.random.randint(100,size =(2,3,5))
obj = soln1(mat1,mat2)
obj.mAdd()

array([[ 70,  92, 115,  99, 157],
       [ 24,  82,  45,  98,  93],
       [ 51, 126,  87,  77,  27],
       [ 78, 107,  90,  81, 148],
       [ 68,  41, 119,  86, 123],
       [ 93,  64, 129, 163, 132]])

In [113]:
mat1 = np.random.randint(100,size=(2,3,5))
mat2 = np.random.randint(100,size =(3,3,5))
obj = soln1(mat1,mat2)
obj.mAdd()

dimensions not same, cant add


# 2) Write a Python Program to Multiply Two Matrices?


In [13]:
class soln1:
    
    def __init__(self,mat1,mat2):
        self.m1 = mat1
        self.m2 = mat2
        self.m2_transposed = []
        self.row_m1 = mat1.shape[0]
        self.col_m1 = mat1.shape[1]
        self.row_m2 = mat2.shape[0]
        self.col_m2 = mat2.shape[1]
        
        
    def mMul(self):
        
        
        try:
            #Dimension Check
            if self.col_m1 != self.row_m2:
                raise Exception("Can't multiply such matrices")
            else:
                
                
                #Transposing matrix m2 
                for i in range(len(self.m2[0])):
                    temp = []
                    for j in range(len(self.m2)):
                        temp.append(self.m2[j][i])
                    self.m2_transposed.append(temp)
                #print(self.m2_transposed)
                
                #multiply matrix m1 and m2_transposed
                res = []
                for i in self.m1:
                    for j in self.m2_transposed:
                        #print(i,j)
                        sum1 = 0
                        for k,l in zip(i,j):
                            sum1+= (k*l)
                        res.append(sum1)
                
                #matrix repr. m1 and m2_transposed multiplication
                #will be of the form self.row_m1,self.col_m2
                finalres = np.reshape(np.array(res),newshape=(self.row_m1,self.col_m2)) 
                return finalres
        
        except Exception as e:
            return e
            

#### eg 1

In [6]:
mat1 = np.array([[1,2,3],[4,5,6]])
mat2 = np.array([[7,8],[9,10],[11,12]])
obj = soln1(mat1,mat2)
print(obj.mMul())

[[ 58  64]
 [139 154]]


#### eg1 verification

In [8]:
mat1 = np.array([[1,2,3],[4,5,6]])
mat2 = np.array([[7,8],[9,10],[11,12]])
mat1@mat2

array([[ 58,  64],
       [139, 154]])

#### eg2

In [7]:
mat1 = np.array([[1,2],[4,5]])
mat2 = np.array([[5,6,7,8],[9,10,11,12]])
obj = soln1(mat1,mat2)
print(obj.mMul())

[[23 26 29 32]
 [65 74 83 92]]


#### eg2 Verification

In [3]:
mat1 = np.array([[1,2],[4,5]])
mat2 = np.array([[5,6,7,8],[9,10,11,12]])
mat1@mat2

array([[23, 26, 29, 32],
       [65, 74, 83, 92]])

#### eg3

In [10]:
mat1 = np.array([[1,2,3],[4,5,6]])
mat2 = np.array([[5,6,7,8],[9,10,11,12]])
obj = soln1(mat1,mat2)
print(obj.mMul())

Can't multiply such matrices
None


#### eg3 Verification

In [12]:
mat1 = np.array([[1,2,3],[4,5,6]])
mat2 = np.array([[5,6,7,8],[9,10,11,12]])
mat1@mat2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

# 3) Write a Python Program to Transpose a Matrix?

In [17]:
class soln3:
    
    def __init__(self,mat1):
        self.m1 = mat1
        self.m1_transposed = []
    
    def mTranspose(self):
        try:
            for i in range(len(self.m1[0])):
                temp = []
                for j in range(len(self.m1)):
                    temp.append(self.m1[j][i])
                self.m1_transposed.append(temp)
        
            return self.m1_transposed
        
        except Exception as e:
            return e

In [18]:
mat1 = np.array([[1,2,3],[4,5,6]])
obj = soln3(mat1)
obj.mTranspose()

[[1, 4], [2, 5], [3, 6]]

# 4) Write a Python Program to Sort Words in Alphabetic Order?

In [34]:
class soln4():
    
    def __init__(self,ls):
        self.input_list = ls
    
    def sortA(self):
        try:
            self.input_list.sort()
            return self.input_list
        except Exception as e:
            return e

In [36]:
ls = ['Cat','Dog','Basket','Apple']
obj = soln4(ls)
print(obj.sortA())

['Apple', 'Basket', 'Cat', 'Dog']


# 5) Write a Python Program to Remove Punctuation From a String?

In [14]:
class soln5():
    def __init__(self,string):
        self.input = string
        self.result = []
    
    def removePunct(self):
        try:
            for i in self.input:
                # Assuming everything other than alphabets and obviously not punctuation marks as 
                # Punctuation marks in the ascii table
                if (32<=ord(i)<=47) or (58<=ord(i)<=64) or (91<=ord(i)<=96) or (123<=ord(i)<=126):
                    pass
                else:
                    self.result.append(i)
        
            return ''.join(self.result)
        
        except Exception as e:
            return e

In [18]:
s = "@!@!@#@!?? abc....>>>def%^&*()ghi"
obj = soln5(s)
print(obj.removePunct())

abcdefghi


In [19]:
s = "@!@!@#@!?? ss $$$$s....>>>AS?><:'dasdd"
obj = soln5(s)
print(obj.removePunct())

sssASdasdd


In [21]:
s = "@!{}{]})()?? abc $$$$d....>>>e?><:'f{]})gh!{}"
obj = soln5(s)
print(obj.removePunct())

abcdefgh
